name: clean_architecture_proposal
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: 2.0.0
  http: 0.12.0
  get_it: 6.0.0
  localstorage: 4.0.0+1
  bloc: 7.0.0
  copy_with_extension: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 1.16.5
  mockito: ^5.0.0
  faker: 1.3.0
  build_runner: ^1.11.5
  copy_with_extension_gen: ^2.0.1

flutter:
  uses-material-design: true
