name: micro_commons_deps
description: A new Flutter package project.
version: 0.0.1
author:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  injectable: ^1.2.2
  get_it: ^6.1.1
  mobx: ^2.0.1
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.5

flutter:
